### ISSUE TITLE
Remove ALL instances for WMOVR approval

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/nft-market#102]
We don't need to allow/approve WMOVR for bid, or any action.. as the contract will wrap and unwrap automatically.
Test after removal to confirm this.

![image](https://user-images.githubusercontent.com/180252/146690630-f01ccd6c-c3b2-4924-a93a-bb8a016678ba.png)

**Comment by prandev01** [comment]
Ok, I will do this.

And one additional question.
Do we need to remove the "Wrap/Unwrap" buttons?
