### ISSUE TITLE
Update Live Auctions to show Instant Bid auctions

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/nft-market#132]
We will need to indicate these Instant Bid Auctions are different and will close on the FIRST Bid placed immediately.
Discuss in this thread before we proceed

![image](https://user-images.githubusercontent.com/180252/147592265-7ff35ff7-a119-4eaa-9584-62fbfa38af7e.png)

**Comment by prandev01** [comment]
- First, I think we can replace the wrong datetime with "Instant Auction"
- Instead of the gray "Remaining time" label, we can display the description of "Instant auction"

What do you think guys?

**Comment by prandev01** [comment]
The instant auctions' auctionEnd property value is ZERO.
So, once the transaction (first apply bid) is done, it is settled.
The issue now is the instant auctions are always returned as "Archived auctions" as 
AuctionEnd < current timestamp
 whatever it is new auction or settled auction.
The backend server returns the instant auctions as "ended auctions".
On the API server, there is no rule to check if the instant auction is live or settled.
