### ISSUE TITLE
Auction ID #29, #34 are duplicated (On Live site).

### ISSUE THREAD

**Issue by prandev01** [ryanprice/nft-market#145]
<img width="483" alt="Screen Shot 2022-01-19 at 12 58 17 PM" src="https://user-images.githubusercontent.com/76412910/150213158-4e64f5be-a99a-473e-848a-35258d239543.png">

**Comment by ryanprice** [comment]
I think this is a front end bug.. here is the data feed , https://api.zoombies.world/listings

**Comment by prandev01** [comment]
It is server side bug.
Please check the logic when offset parameter is included in the payload.

You can compare the results with these two requests.

https://api.zoombies.world/listings?cardOrigin=&saleToken=&cardRarity=&search=&sortBy=auctionEnd&offset=undefined&limit=5&status=

https://api.zoombies.world/listings?cardOrigin=&saleToken=&cardRarity=&search=&sortBy=auctionEnd&offset=5&limit=5&status=

**Comment by prandev01** [comment]
This issue is solved by 
https://github.com/ryanprice/api-zoombies-world/issues/17
