### ISSUE TITLE
Auction #2 has 2 cards but only showing 1 in home 

### ISSUE THREAD

**Issue by mchigit** [ryanprice/nft-market#75]
![image](https://user-images.githubusercontent.com/19379512/145736708-7b75ed46-d6b8-4b3a-adc7-411d65ce50ec.png)

**Comment by ryanprice** [comment]
maybe this is fixed now ?

**Comment by mchigit** [comment]
> maybe this is fixed now ?

I believe so. @jjjhill was investigating this issue, and it didn't seem like a bug in the code. It looked like the data might've been corrupted when we did the contract update. I haven't seen this issue popup anymore
