### ISSUE TITLE
Investigate allowance and approving

### ISSUE THREAD

**Issue by mchigit** [ryanprice/nft-market#95]
There's some weird behavior when it comes to approving zoom burn, and setting allowance. I'm guessing we are not using the correct contract methods or there are cases we are not handling. 

For example, I can set a zoom allowance of 800k, but I still need to approve for a zoom burn of 10000, which doesn't make sense. After I create a listiing, the `.allowance` method is not returning 800k - 10000. 

Here is what I think the correct behaviour should be:
- User sets an allowance as high as they want
- When creating a listing, if allowance is higher than zoom burn fee, user shouldn't need to approve
- After creating a listing, the user allowance should be `previousAllowance - zoomFeeBurned`

**Comment by ryanprice** [comment]
This is resolved now with using increase and decrease and BigNumber object
