### ISSUE TITLE
Heart Button doesn't do anything

### ISSUE THREAD

**Issue by jjjhill** [ryanprice/nft-market#98]
![image](https://user-images.githubusercontent.com/16979310/146685030-55e6341b-2db3-4e65-bd2b-d0a699112684.png)

**Comment by mchigit** [comment]
We can potentially use localStorage for this. But the data will be lost if that storage is cleared. If we want to associate like with a user permanently, we need it to be in the DB.

**Comment by jjjhill** [comment]
@ryanprice do you want to spend time on this? or remove the "heart" feature from the UI for now?

**Comment by ryanprice** [comment]
sure let's hide this or remove the heart for now until we scope the user stuff.
